server:
  port: 9049

spring:
  datasource:
    url: jdbc:postgresql://43.205.24.208:5432/attendance_db
    username: postgres
    password: pgadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret: moOXvdGYZYWKuHAtzFQIpOqaKif8lmG0nGjtPSP+utQ=
  expiration: 3600000



